name: build

on:
  # Run on pushes to tags, the "master" branch, and PR's
  push:
    tags-ignore:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '*.txt'
      - '.gitignore'
      - 'docs/*'
  pull_request:
    paths-ignore:
      - '**.md'
      - '*.txt'
      - '.gitignore'
      - 'docs/*'

  workflow_dispatch:

jobs:
  windows-msvc:
    name: ${{ matrix.config }} Windows ${{ matrix.arch }}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        #arch: [arm64, x86, x64]
        #arch: [x86, x64]
        arch: [x86, x64]
        config: [Release]
        include:
         # - arch: arm64
         #   platform: ARM64
         #   suffix: .arm64
         #   pkg_suffix: arm64

          - arch: x86
            platform: Win32
            pkg_suffix: x86

          - arch: x64
            platform: x64
            suffix: .x64
            pkg_suffix: x64

    steps:
    - uses: microsoft/setup-msbuild@v1.0.2

    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Build Engine
      working-directory: ${{github.workspace}}/src
      run: |
        msbuild win32\msvc2017\wolfded.vcxproj -m -p:PlatformToolset=v141_xp,TargetName=ETe.ded,Configuration=${{ matrix.config }},Platform=${{ matrix.platform }}
        msbuild win32\msvc2017\renderer.vcxproj -m -p:PlatformToolset=v141_xp,Configuration=${{ matrix.config }},Platform=${{ matrix.platform }}
        msbuild win32\msvc2017\wolf.vcxproj -m -p:PlatformToolset=v141_xp,TargetName=ETe,Configuration=${{ matrix.config }},Platform=${{ matrix.platform }},UseWasapi=USE_WASAPI=0

    - name: Build etmain
      working-directory: ${{github.workspace}}/src
      run: |
        msbuild win32\msvc2017\game.vcxproj -m -p:PlatformToolset=v141_xp,Configuration=${{ matrix.config }},Platform=${{ matrix.platform }}
        msbuild win32\msvc2017\ui.vcxproj -m -p:PlatformToolset=v141_xp,Configuration=${{ matrix.config }},Platform=${{ matrix.platform }}
        msbuild win32\msvc2017\cgame.vcxproj -m -p:PlatformToolset=v141_xp,Configuration=${{ matrix.config }},Platform=${{ matrix.platform }}

    - name: Create Binary Directory
      working-directory: ${{github.workspace}}
      run: mkdir bin

    - name: Copy outputs to Binary Directory
      working-directory: ${{github.workspace}}/src
      run: |
          copy win32\msvc2017\output\${{ matrix.config }}\ETe.ded.exe ${{github.workspace}}\bin\ETe.ded${{ matrix.suffix }}.exe
          copy win32\msvc2017\output\${{ matrix.config }}\ETe.exe ${{github.workspace}}\bin\ETe${{ matrix.suffix }}.exe

          copy win32\msvc2017\output\${{ matrix.config }}\qagame_mp_${{ matrix.pkg_suffix }}.dll ${{github.workspace}}\bin\
          copy win32\msvc2017\output\${{ matrix.config }}\ui_mp_${{ matrix.pkg_suffix }}.dll ${{github.workspace}}\bin\
          copy win32\msvc2017\output\${{ matrix.config }}\cgame_mp_${{ matrix.pkg_suffix }}.dll ${{github.workspace}}\bin\

    - uses: actions/upload-artifact@v2
      if: ${{ matrix.config == 'Release' }}
      with:
        name: windows-${{ matrix.pkg_suffix }}
        path: |
          bin/*.exe
          bin/*.dll
        if-no-files-found: error
        retention-days: 5

  ubuntu-x86:
    name: ${{ matrix.config }} Ubuntu ${{ matrix.arch }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        arch: [x86, x86_64]
        cc: [gcc]
        cxx: [g++]
        config: [Release]
        include:
          - config: Release
            rule: install
          - arch: x86
            use_sdl: true
          - arch: x86_64
            use_sdl: true

    steps:
    - name: Install tools
      run: |
        if [ ${{ matrix.arch }} == "x86" ]; then
          sudo dpkg --add-architecture i386
          sudo apt-get -qq update
          sudo apt-get -y install gcc-multilib g++-multilib ninja-build
          sudo apt-get -y install --allow-downgrades libpcre2-8-0=10.34-7 libglib2.0-dev:i386 libjpeg-dev:i386 libsdl2-dev:i386 libcurl4-openssl-dev:i386
        else
          sudo apt-get -qq update
          sudo apt-get -y install ninja-build libglib2.0-dev libjpeg-dev libsdl2-dev libcurl4-openssl-dev
        fi
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Create Build Directory
      working-directory: ${{github.workspace}}/src
      run: cmake -E make_directory ${{github.workspace}}/src/bin

    - name: Configure CMake (Engine)
      working-directory: ${{github.workspace}}/src/bin
      run: |
        if [ ${{ matrix.arch }} == "x86" ]; then
          cmake .. -G "Ninja" -DCMAKE_BUILD_TYPE=${{ matrix.config }} -DUSE_SDL2=${{ matrix.use_sdl }} -DBUILD_ETMAIN_MOD=OFF -DCMAKE_TOOLCHAIN_FILE=../cmake/toolchains/linux-i686.cmake
        else
          cmake .. -G "Ninja" -DCMAKE_BUILD_TYPE=${{ matrix.config }} -DUSE_SDL2=${{ matrix.use_sdl }} -DBUILD_ETMAIN_MOD=OFF
        fi

    - name: Build (Engine)
      working-directory: ${{github.workspace}}/src/bin
      run: cmake --build . --config ${{ matrix.config }} --parallel

    - name: Configure CMake (etmain)
      working-directory: ${{github.workspace}}/src/bin
      run: |
        rm CMakeCache.txt
        if [ ${{ matrix.arch }} == "x86" ]; then
          cmake .. -G "Ninja" -DCMAKE_BUILD_TYPE=${{ matrix.config }} -DBUILD_DEDSERVER=OFF -DBUILD_CLIENT=OFF -DBUILD_ETMAIN_MOD=ON -DCMAKE_TOOLCHAIN_FILE=../cmake/toolchains/linux-i686.cmake
        else
          cmake .. -G "Ninja" -DCMAKE_BUILD_TYPE=${{ matrix.config }} -DBUILD_DEDSERVER=OFF -DBUILD_CLIENT=OFF -DBUILD_ETMAIN_MOD=ON
        fi

    - name: Build (etmain)
      working-directory: ${{github.workspace}}/src/bin
      run: cmake --build . --config ${{ matrix.config }} --parallel

    - uses: actions/upload-artifact@v2
      if: matrix.cc == 'gcc' && matrix.config == 'Release'
      with:
        name: linux-${{ matrix.arch }}
        path: |
          src/bin/ete*.${{ matrix.arch }}
          src/bin/*.so
        if-no-files-found: error
        retention-days: 5

  macos-x86:
    name: ${{ matrix.config }} macOS ${{ matrix.arch }}
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64]
        cc: [clang]
        cxx: [clang++]
        config: [Release]
        include:
          - config: Release
            rule: install

    steps:
    - name: Install tools
      run: brew install coreutils ninja sdl2

    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Create Build Directory
      working-directory: ${{github.workspace}}/src
      run: cmake -E make_directory ${{github.workspace}}/src/bin

    - name: Configure CMake (Engine)
      working-directory: ${{github.workspace}}/src/bin
      run: cmake .. -G "Ninja" -DCMAKE_BUILD_TYPE=${{ matrix.config }} -DUSE_SDL2=TRUE -DBUILD_ETMAIN_MOD=OFF

    - name: Build (Engine)
      working-directory: ${{github.workspace}}/src/bin
      run: cmake --build . --config ${{ matrix.config }} --parallel

    - name: Configure CMake (etmain)
      working-directory: ${{github.workspace}}/src/bin
      run: |
        rm CMakeCache.txt
        cmake .. -G "Ninja" -DCMAKE_BUILD_TYPE=${{ matrix.config }} -DBUILD_DEDSERVER=FALSE -DBUILD_CLIENT=FALSE -DBUILD_ETMAIN_MOD=TRUE

    - name: Build (etmain)
      working-directory: ${{github.workspace}}/src/bin
      run: cmake --build . --config ${{ matrix.config }} --parallel

    - uses: actions/upload-artifact@v2
      if: matrix.cc == 'clang' && matrix.config == 'Release'
      with:
        name: macos-${{ matrix.arch }}
        path: |
          src/bin/ete*.${{ matrix.arch }}
          src/bin/*_mac
        if-no-files-found: error
        retention-days: 5

  create-testing:
    if: github.ref == 'refs/heads/master' && github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    needs: [windows-msvc, ubuntu-x86, macos-x86]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Download Artifacts
        uses: actions/download-artifact@v2

      - name: Create binary archives
        run: |
          7z a -r ete-linux-x86.zip            ./linux-x86/* -x!*.so
          7z a -r ete-linux-x86_64.zip         ./linux-x86_64/* -x!*.so
          7z a -r ete-windows-msvc-x86.zip     ./windows-x86/* -x!*.dll
          7z a -r ete-windows-msvc-x64.zip     ./windows-x64/* -x!*.dll
          7z a -r ete-macos-x86_64.zip         ./macos-x86_64/* -x!*_mac
          mkdir -p etmain
          mv -t  ./etmain/ ./linux-x86/*.so
          mv -t  ./etmain/ ./linux-x86_64/*.so
          mv -t  ./etmain/ ./windows-x86/*.dll
          mv -t  ./etmain/ ./windows-x64/*.dll
          mv -t  ./etmain/ ./macos-x86_64/*_mac
          cd etmain
          7z a -r -tzip mp_bina.pk3      ./cgame*.so
          7z a -r -tzip mp_bina.pk3      ./ui*.so
          7z a -r -tzip mp_bina.pk3      ./cgame*.dll
          7z a -r -tzip mp_bina.pk3      ./ui*.dll
          7z a -r -tzip mp_bina.pk3      ./cgame_mac
          7z a -r -tzip mp_bina.pk3      ./ui_mac
          cd ..
          7z a -r ete-etmain-mod-replacement-allplatform.zip      ./etmain/*.pk3
          7z a -r ete-etmain-mod-replacement-allplatform.zip      ./etmain/*.so
          7z a -r ete-etmain-mod-replacement-allplatform.zip      ./etmain/*.dll
          7z a -r ete-etmain-mod-replacement-allplatform.zip      ./etmain/*_mac

      - name: Create Client Hashes
        run: |
          md5sum ./linux-x86/ete.x86 > ete.x86.md5
          sha1sum ./linux-x86/ete.x86 > ete.x86.sha1
          7z a -r ete-client-hashes.zip ete.x86.md5 ete.x86.sha1
          md5sum ./linux-x86_64/ete.x86_64 > ete.x86_64.md5
          sha1sum ./linux-x86_64/ete.x86_64 > ete.x86_64.sha1
          7z a -r ete-client-hashes.zip ete.x86_64.md5 ete.x86_64.sha1
          md5sum ./windows-x86/ETe.exe > ETe.exe.md5
          sha1sum ./windows-x86/ETe.exe > ETe.exe.sha1
          7z a -r ete-client-hashes.zip ETe.exe.md5 ETe.exe.sha1
          md5sum ./windows-x64/ETe.x64.exe > ETe.x64.exe.md5
          sha1sum ./windows-x64/ETe.x64.exe > ETe.x64.exe.sha1
          7z a -r ete-client-hashes.zip ETe.x64.exe.md5 ETe.x64.exe.sha1
          md5sum ./macos-x86_64/ete.x86_64 > ete_mac.x86_64.md5
          sha1sum ./macos-x86_64/ete.x86_64 > ete_mac.x86_64.sha1
          7z a -r ete-client-hashes.zip ete_mac.x86_64.md5 ete_mac.x86_64.sha1

#TODO other builds
#NOTE purposely skipping etmain for macos as it is not really functional
#7z a -r ete-windows-mingw-x86.zip    ./windows-mingw-x86/* -x!*.dll
#7z a -r ete-windows-mingw-x86_64.zip ./windows-mingw-x86_64/* -x!*.dll
#7z a -r ete-windows-msvc-arm64.zip   ./windows-arm64/* -x!*.dll
#7z a -r ete-macos-arm64.zip         ./macos-arm64/* -x!*.dylib
#7z a -r ete-linux-aarch64.zip  ./linux-aarch64/*
#7z a -r ete-linux-armv7.zip    ./linux-armv7/*
#7z a -r -tzip mp_bina.pk3      ./*.dylib

      - name: Create docs archive
        run: |
          7z a -r ete-docs.zip ./docs/*

      - name: Create latest build
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: "latest"
          prerelease: false
          title: Latest Build
          files: |
            *.zip
